name: Build and Deploy site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove global .npmrc
        run: rm -f ~/.npmrc

      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies using a safe clean install, build and test
        run: |
          npm install

      - name: Run Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}

      - name: Build Eleventy
        run: npm run build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci

      - name: Copy vendor assets
        run: |
          npm run copy-css || true
          npm run copy-js || true
          npm run copy-fa || true
          npm run copy-chartjs || true
          if [ -d node_modules/caswow.library ]; then
            npm run copy-cas || true
          else
            echo "caswow.library not present — skipping npm run copy-cas"
          fi

      - name: Build CSS
        run: npm run css

      - name: Build Eleventy
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./docs
          publish_branch: gh-pages
          # Use the default GITHUB_TOKEN so the action can push; repo must enable GitHub Pages from gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
